import { Poppins , Montserrat_Alternates } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins-sans",
  subsets: ["latin"],
  weight : ['400' , '500' , '600' , '700' , '900']
});

const Montserrat = Montserrat_Alternates({
  variable: "--font-montserrat-mono",
  subsets: ["latin"],
  weight : ['400' , '500' , '600' , '900']
});

export const metadata = {
  title: "New Shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${Montserrat.variable}`}>
        {children}
      </body>
    </html>
  );
}
